<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>BuckarooSdk</RootNamespace>
		<AssemblyName>BuckarooSdk</AssemblyName>
		<Description>.NET Standard SDK for the Buckaroo API</Description>
		<PackageId>BuckarooSdk</PackageId>
		<Authors>Buckaroo</Authors>
		<Company>Buckaroo</Company>
		<Copyright>Copyright © Buckaroo</Copyright>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/buckaroo-it/BuckarooSdk_DotNet</PackageProjectUrl>
		<RepositoryUrl>https://github.com/buckaroo-it/BuckarooSdk_DotNet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>buckaroo;payments;payment;psp;ideal;creditcard;sdk</PackageTags>
		<PackageIconUrl>https://www.buckaroo.nl/assets/static/favicons/apple-touch-icon.png</PackageIconUrl>
	</PropertyGroup>

	<ItemGroup>
		<None Include="../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="DataTypes\GlobalGroups\" />
		<Folder Include="Services\CreditCards\BanContact\Constants\" />
		<Folder Include="Services\CreditManagement\Push\" />
		<Folder Include="Services\iDin\Constants\" />
		<Folder Include="Services\iDin\DataRequest\" />
		<Folder Include="Services\Payconiq\Push\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
	</ItemGroup>

</Project>