namespace BuckarooSdk.Services.Ideal.Constants
{
    public enum OutputParameters
    {
        ConsumerBic,
        ConsumerName,
        ConsumerIssuer,
        ConsumerIban,
        ContactDetailsFirstName,
        ContactDetailsLastName,
        ContactDetailsPhoneNumber,
        ContactDetailsEmail,
        ShippingAddressFirstName,
        ShippingAddressLastName,
        ShippingAddressCompanyName,
        ShippingAddressPostalCode,
        ShippingAddressAddition,
        ShippingAddressHouseNumber,
        ShippingAddressStreet,
        ShippingAddressCity,
        ShippingAddressCountryName,
        InvoiceAddressFirstName,
        InvoiceAddressLastName,
        InvoiceAddressCompanyName,
        InvoiceAddressPostalCode,
        InvoiceAddressAddition,
        InvoiceAddressHouseNumber,
        InvoiceAddressStreet,
        InvoiceAddressCity,
        InvoiceAddressCountryName
    }
}
